include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - example/build/**
  errors:
    lines_longer_than_80_chars: ignore

linter:
  rules:
    lines_longer_than_80_chars: false

formatter:
  page_width: 120
